
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author olubusolamisogunle
 */
public class course_2 extends javax.swing.JFrame {

    /**
     * Creates new form course1
     */
    String course_code,username;
    int s;
    public course_2(String code,int val,String uname) {
        initComponents();
        s=val;
        username=uname;
        course_code=code;
        jProgressBar1.setValue(0);
        jProgressBar1.setStringPainted(true);
        jProgressBar1.setMaximum(5);
        jProgressBar1.setMinimum(0);
        setvalues(code);
    }
    public void setvalues(String c){
        try{
            Connection conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/tracker", "root","");
            String sql= "SELECT * FROM courses WHERE code='" + c +"'";
            PreparedStatement ps=(PreparedStatement) conn.prepareStatement(sql);
            ResultSet rs =ps.executeQuery();
            rs.next();
            
            jLabel1.setText(rs.getString(1)+":");
            jLabel2.setText(rs.getString(2));
            jLabel3.setText((jLabel3.getText()+rs.getInt(3))+"");
            jLabel4.setText(jLabel4.getText()+rs.getInt(4)+"");
            jLabel5.setText(jLabel5.getText()+rs.getInt(5)+"");
            
            if(rs.getInt(6)==1){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                jCheckBox1.setSelected(true);
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue());
                jCheckBox1.setSelected(false);
            }
            
            if(rs.getInt(7)==1){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                jCheckBox2.setSelected(true);
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue());
                jCheckBox2.setSelected(false);
            }
            
            if(rs.getInt(8)==1){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                jCheckBox3.setSelected(true);
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue());
                jCheckBox3.setSelected(false);
            }
            if(rs.getInt(9)==1){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                jCheckBox4.setSelected(true);
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue());
                jCheckBox4.setSelected(false);
            }
            if(rs.getInt(10)==1){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                jCheckBox5.setSelected(true);
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue());
                jCheckBox5.setSelected(false);
            }
          //  jLabel1.setText(rs.getString(1));
          //  jLabel1.setText(rs.getString(1));
          //  jLabel1.setText(rs.getString(1));
          
        }
        catch(Exception ex){
        System.out.println(ex);
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Course code ");

        jLabel2.setFont(new java.awt.Font("Nunito", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Course Title");

        jLabel3.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current week: ");

        jLabel4.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Unit: ");

        jLabel5.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number of students: ");

        jProgressBar1.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox1.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Conduct test1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Conduct test2");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Upload test scores");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Set and submit examination questions");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Submit examination results");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Course Progress");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jLabel6))
                        .addContainerGap(230, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox5)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
         try{
            Connection conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/tracker", "root","");
            String sql;
            if(jCheckBox2.isSelected()==true){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                sql= "UPDATE courses SET test2=1 WHERE code='"+course_code+"'";
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue()-1);
                sql= "UPDATE courses SET test2=0 WHERE code='"+course_code+"'";
            }
            PreparedStatement ps=(PreparedStatement) conn.prepareStatement(sql);
            ps.executeUpdate();
            
            ps.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error occured"+e.getMessage());
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/tracker", "root","");
            String sql;
            if(jCheckBox1.isSelected()==true){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                sql= "UPDATE courses SET test1=1 WHERE code='"+course_code+"'";
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue()-1);
                sql= "UPDATE courses SET test1=0 WHERE code='"+course_code+"'";
            }
            PreparedStatement ps=(PreparedStatement) conn.prepareStatement(sql);
            ps.executeUpdate();
            
            ps.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error occured"+e.getMessage());
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/tracker", "root","");
            String sql;
            if(jCheckBox3.isSelected()==true){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                sql= "UPDATE courses SET upload_scores=1 WHERE code='"+course_code+"'";
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue()-1);
                sql= "UPDATE courses SET upload_scores=0 WHERE code='"+course_code+"'";
            }
            PreparedStatement ps=(PreparedStatement) conn.prepareStatement(sql);
            ps.executeUpdate();
            
            ps.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error occured"+e.getMessage());
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/tracker", "root","");
            String sql;
            if(jCheckBox4.isSelected()==true){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                sql= "UPDATE courses SET exam_que=1 WHERE code='"+course_code+"'";
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue()-1);
                sql= "UPDATE courses SET exam_que=0 WHERE code='"+course_code+"'";
            }
            PreparedStatement ps=(PreparedStatement) conn.prepareStatement(sql);
            ps.executeUpdate();
            
            ps.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error occured"+e.getMessage());
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/tracker", "root","");
            String sql;
            if(jCheckBox5.isSelected()==true){
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
                sql= "UPDATE courses SET exam_result=1 WHERE code='"+course_code+"'";
            }
            else{
                jProgressBar1.setValue(jProgressBar1.getValue()-1);
                sql= "UPDATE courses SET exam_result=0 WHERE code='"+course_code+"'";
            }
            PreparedStatement ps=(PreparedStatement) conn.prepareStatement(sql);
            ps.executeUpdate();
            
            ps.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error occured"+e.getMessage());
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        home Home=new home(s,username);
        Home.getContentPane().setBackground(Color.BLACK);
        Home.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(course1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(course1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(course1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(course1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new course_2("",0,"").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
